version: '3.8'

services:

  web:
    build: .
    ports:
      - "8080:80"
    environment:
      - APP_ENV=development
    depends_on:
      - db

  db:
    image: mysql:8
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password

volumes:
  db_data:
